apiVersion: v1
kind: Service
metadata:
  name: td-synnex-scraper
  namespace: scraper
  labels:
    app: td-synnex-scraper
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: health
  selector:
    app: td-synnex-scraper
---
apiVersion: v1
kind: Namespace
metadata:
  name: scraper
---
apiVersion: v1
kind: Secret
metadata:
  name: td-synnex-credentials
  namespace: scraper
type: Opaque
stringData:
  username: YOUR_TDSYNNEX_USERNAME
  password: YOUR_TDSYNNEX_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: email-credentials
  namespace: scraper
type: Opaque
stringData:
  username: YOUR_EMAIL_USERNAME
  password: YOUR_EMAIL_PASSWORD