version: '3.8'

services:
  # Email Verification Service
  email-verification-service:
    build: 
      context: ./email-verification-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - OUTLOOK_USER_EMAIL=${OUTLOOK_USER_EMAIL:-pgits@hexalinks.com}
      - PORT=5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - scraper-network

  # Main TD SYNNEX Scraper Service
  td-synnex-scraper:
    build: 
      context: .
      dockerfile: Dockerfile.container-apps
    ports:
      - "8080:8080"
    environment:
      - TDSYNNEX_USERNAME=${TDSYNNEX_USERNAME}
      - TDSYNNEX_PASSWORD=${TDSYNNEX_PASSWORD}
      - EMAIL_SERVICE_URL=http://email-verification-service:5000
      - PORT=8080
    depends_on:
      email-verification-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - scraper-network

networks:
  scraper-network:
    driver: bridge